### ISSUE TITLE
getViewStrategy() is not invoked when model data change

### ISSUE THREAD

**Issue by thomas-jakemeyn** [aurelia/templating-router#11]
As stated in the Aurelia documentation, the view to be associated with a view model can be determined dynamically by implementing the method *getViewStrategy* in the view model. This method is executed after the *activate* callback, so the model data can be accessed when determining the view.

I am creating a simple component whose goal is to display notifications (errors, warnings and success messages). The view is as followed.
```html
<template>
    <compose if.bind="!!error" model.bind="error" view-model="./error/error"></compose>
</template>
```
So, if there is an error, it is displayed by the *error* sub-component. Since I have to handle many types of errors which must be displayed in different ways, I have implemented the method *getViewStrategy* on the view model of that sub-component.
```javascript
import {activationStrategy} from 'aurelia-router';

export class Error {

    determineActivationStrategy() {
        return activationStrategy.replace;
    }

    activate(error) {
        this.error = error;
    }

    getViewStrategy() {
        if (this.error.code === 'error.validation') {
            return './error.validation.html';
        }
        return './error.default.html';
    }
}
```
The first error is always displayed by the correct view. However, when the error changes, the new error is correctly bound but the view stays the same.

When debugging, I noticed that, the first time an error is set, both *activate* and *getViewStrategy* are invoked. When the error changes, *activate* is correctly invoked but *getViewStrategy* is not.

After a quick investigation, I think that the problem is located in the file *router-view.js*.
```javascript
if (!viewStrategy && 'getViewStrategy' in viewModel) {
      viewStrategy = viewModel.getViewStrategy();
}
```
If *viewStrategy* is already defined, then *getViewStrategy* is not invoked. 

Since the view is determined based on the model data as explained in the documentation, I would expect the method *getViewStrategy* to be re-invoked if those data change, even if a view has already been determined.

**Comment by Tinloon** [comment]
Since the VM's life-cycle is called only once you may have problems to recognize that the user switched the route. Try implementing determineActivationStrategy in the view modal :

import {activationStrategy} from 'aurelia-router';
export class YourViewModel {
    determineActivationStrategy() {
        return activationStrategy.replace;
    }
}

If you just want to force a refresh of the life-cycle (useful with <compose> bindings) you may do something like the following:

import {activationStrategy} from 'aurelia-router';
export class YourViewModel {
  determineActivationStrategy(){
    return activationStrategy.invokeLifecycle;
  }
}
