### ISSUE TITLE
ViewSlot error on 1.5.0

### ISSUE THREAD

**Issue by michaelbull** [aurelia/templating-router#130]
**I'm submitting a bug report**

* **Library Version:**
1.5.0

* **Node Version:**
14.19.0

* **NPM Version:**
6.14.16

* **JSPM OR Webpack AND Version**
Webpack 5

* **Browser:**
all 

* **Language:**
all 

**Current behavior:**

The latest release, 1.5.0, seems to completely break my app. The following stacktrace occurs:

```Error: Error invoking ViewSlot. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: Cannot set properties of undefined (setting 'viewSlot')
Inner Error Stack:
TypeError: Cannot set properties of undefined (setting 'viewSlot')
    at new ViewSlot (aurelia-templating.jss:1291:1)
    at Object.invoke (aurelia-dependency-injection.jss:384:1)
    at InvocationHandler.invoke (aurelia-dependency-injection.jss:357:1)
    at Container.invoke (aurelia-dependency-injection.jss:543:1)
    at StrategyResolver.get (aurelia-dependency-injection.jss:101:1)
    at Container._get (aurelia-dependency-injection.jss:504:1)
    at Container.get (aurelia-dependency-injection.jss:494:1)
    at Container.elementContainerGet [as get] (aurelia-templating.jss:2336:1)
    at aurelia-dependency-injection.jss:383:51
    at Array.map (<anonymous>)
End Inner Error Stack
------------------------------------------------

    at new AggregateError (aurelia-pal.jss:30:1)
    at Container.invoke (aurelia-dependency-injection.jss:546:1)
    at StrategyResolver.get (aurelia-dependency-injection.jss:101:1)
    at Container._get (aurelia-dependency-injection.jss:504:1)
    at Container.get (aurelia-dependency-injection.jss:494:1)
    at Container.elementContainerGet [as get] (aurelia-templating.jss:2336:1)
    at aurelia-dependency-injection.jss:383:51
    at Array.map (<anonymous>)
    at Object.invoke (aurelia-dependency-injection.jss:383:1)
    at InvocationHandler.invoke (aurelia-dependency-injection.jss:357:1)```
```

**Comment by bigopon** [comment]
@michaelbull you are reporting an issue related to `templating` in `templating-router` repo. So I guess:
- your app upgraded to `templating@1.11.1` just fine?
- then your app crashes when upgraded `templating-router@1.5.0`?

Can you also run
```
npm ls aurelia-templating
```

to see if there's any duplication of modules?

**Comment by michaelbull** [comment]
The version of templating is just derived from one of the other aurelia dependencies (I'm guessing bootstrapper?)

Here is the **non-working version** of `aurelia-templating`: 

```
> $ npm ls aurelia-templating
@my-company/my-app@1.1.83 /home/michael/code/my-app
├─┬ @my-company/ui-component-popup@0.3.51
│ └─┬ aurelia-portal-attribute@1.4.0
│   └── aurelia-templating@1.10.4  deduped
├─┬ @my-company/ui-shared@0.3.51
│ ├─┬ aurelia-bootstrapper@2.3.3
│ │ └── aurelia-templating@1.10.4  deduped
├─┬ aurelia-configuration@2.0.0
│ ├─┬ aurelia-framework@1.3.1
│ │ └── aurelia-templating@1.10.4  deduped
│ ├── aurelia-templating@1.10.4 
│ └─┬ aurelia-templating-binding@1.5.3
│   └── aurelia-templating@1.10.4  deduped
├─┬ aurelia-i18n@3.1.4
│ ├── aurelia-templating@1.10.4  deduped
│ └─┬ aurelia-templating-resources@1.13.0
│   └── aurelia-templating@1.10.4  deduped
├─┬ aurelia-templating-router@1.5.0
│ └── aurelia-templating@1.11.1 
└─┬ aurelia-ui-virtualization@1.0.0-rc2
  └── aurelia-templating@1.10.4  deduped
```

---

Explicitly installing v1.4.0 of `aurelia-templating-router` entirely fixes this problem. Here is the output of `npm ls aurelia-templating` with this **working version** installed:

```
> $ npm ls aurelia-templating
@my-company/my-app@1.1.83 /home/michael/code/my-app
├─┬ @my-company/ui-component-popup@0.3.51
│ └─┬ aurelia-portal-attribute@1.4.0
│   └── aurelia-templating@1.10.4  deduped
├─┬ @my-company/ui-shared@0.3.51
│ ├─┬ aurelia-bootstrapper@2.3.3
│ │ └── aurelia-templating@1.10.4  deduped
│ └─┬ aurelia-templating-router@1.4.0
│   └── aurelia-templating@1.10.4  deduped
├─┬ aurelia-configuration@2.0.0
│ ├─┬ aurelia-framework@1.3.1
│ │ └── aurelia-templating@1.10.4  deduped
│ ├── aurelia-templating@1.10.4 
│ └─┬ aurelia-templating-binding@1.5.3
│   └── aurelia-templating@1.10.4  deduped
├─┬ aurelia-i18n@3.1.4
│ ├── aurelia-templating@1.10.4  deduped
│ └─┬ aurelia-templating-resources@1.13.0
│   └── aurelia-templating@1.10.4  deduped
├─┬ aurelia-templating-router@1.4.0
│ └── aurelia-templating@1.10.4  deduped
└─┬ aurelia-ui-virtualization@1.0.0-rc2
  └── aurelia-templating@1.10.4  deduped
```

**Comment by bigopon** [comment]
@michaelbull I think you are getting 2 different versions of templating with `1.5.0`
![image](https://user-images.githubusercontent.com/9994529/163073673-05696068-0b62-4ec7-9be0-4a75fb78e1fb.png)

can you explicitly install the latest version of `templating` & `templating-router` together?

**Comment by michaelbull** [comment]
I can confirm that with `aurelia-templating-router@1.5.0` & `aurelia-templating@1.11.1` it does indeed work.

This must mean that anyone that installs the latest `aurelia-bootstrapper` with `aurelia-ui-virtualization` is going to hit this problem though surely? This would indicate that they are depending on dynamic versions of `aurelia-templating` and some breaking change has occurred and has been automatically picked up by `npm install` because of the version not being explicitly pinned.

**Comment by bigopon** [comment]
@michaelbull yes that's unfortunately will be the case. One does not need to pin everything though, probably only need to pin the 2 most important one: `aurelia-binding` and `aurelia-templating`. It probably should suffice. I'm not sure how else this issue can be solved.

**Comment by bigopon** [comment]
for `aurelia-binding`, apps generated from our cli will have it aliased to the top level module in `node_modules` and it will work. Maybe we should do the same thing for `aurelia-templating`?
cc @3cp

**Comment by michaelbull** [comment]
May I ask why a breaking change was pushed without incrementing the major version? That's the crux of this issue. If all of
To clarify, both `aurelia-templating-router` and `aurelua-ui-virtualization` are **first-party** Aurelia projects. These projects are written with dynamic versions indicating that they can be updated as long as the major doesn't change, then surely the major version should be changing if a breaking change occurs?

**Comment by bigopon** [comment]
If
- `aurelia-templating-router@1.5.0` requires `aurelia-templating@^1.11.1`, and
- `aurelia-ui-virtualization@any` requires `aurelia-templating@^1.8.0`

then installing `aurelia-templating-router@1.5.0` should bring the common dependency `aurelia-templating` to `1.11.1`. Shouldn't this be the expectation (or did I miss what the point in your question)?

**Comment by michaelbull** [comment]
That is not my expectation as I do not have an explicit dependency on `aurelia-templating-router`.

I have the following in my 'shared' project (which acts as a base for all Aurelia apps within my company):

```
    "aurelia-bootstrapper": "2.3.3",
    "aurelia-http-client": "1.3.1",
    "aurelia-loader-nodejs": "1.1.0",
    "aurelia-pal-nodejs": "2.0.0",
    "aurelia-webpack-plugin": "5.0.3"
```

Then in my individual apps I have:

```
    "my-shared-project": "...",
    "aurelia-configuration": "2.0.0",
    "aurelia-i18n": "3.1.4",
    "aurelia-ui-virtualization": "1.0.0-rc2",
```

Last week this worked. This week, because of the versions not being explicit, I run `npm install` without changing **a single one** of these versions, and everything breaks because the versions have somehow resolved `aurelia-templating-router` to a version that isn't compatible with something else.

If you are following semver, and are using dynamic dependency versions in all of the first-class Aurelia projects, then how can this happen unless a breaking change has been made in one of these libraries without bumping a major version?

**Comment by bigopon** [comment]
This part
> the versions have somehow resolved aurelia-templating-router to a version that isn't compatible with something else.

confused me. My understanding is `npm install` should resolve to a single, latest version of templating.

> If you are following semver, and are using dynamic dependency versions in all of the first-class Aurelia projects, then how can this happen unless a breaking change has been made in one of these libraries without bumping a major version?

I'll assume this is a rhetorical question, and you can explain why `npm install` behaved in such way. So if you can give some comment explaining that, it'd be great.

For `a breaking change has been made in one of these libraries without bumping a major version`: there's been one breaking change here: https://github.com/aurelia/templating-resources/pull/411/files#diff-c2551d45d62d2a8cbbe2fbb4b9430778e2215efe0f345b6d709fa5bd8edeb360R10-R11 though we won't be strictly following semver for this instance, as it would unnecessarily create more trouble. The lib `aurelia-templating-resources` was bumped 1 minor version for that "security" resolution.

EDIT: and in practical terms, one is expected not to use the default HTML sanitizer for dealing with arbitrary user input.

**Comment by bigopon** [comment]
Regardless of this discussion, I'm upgrading all the core libs to be pointing at the latest version of templating/templating-resources/framework to resolve the mentioned security issue. Future installation shouldn't cause any issues.

**Comment by michaelbull** [comment]
> My understanding is npm install should resolve to a single, latest version of templating.

Yes, I agree because the version of templating that I am pulling from bootstrapper or whever is dynamic and will take the latest 1.x version.

> 'll assume this is a rhetorical question, and you can explain why npm install behaved in such way. So if you can give some comment explaining that, it'd be great.

I was trying to explain the original question that you asked if it matches my expectation.

>  though we won't be strictly following semver for this instance, as it would unnecessarily create more trouble

This answers my question.

All of the Aurelia projects have dynamic dependency versions on "1.x" of others, which means consumers will just auto-upgrade when running `npm install`, and they will break their app because they unknowingly adopted a breaking change via a transitive dependency chain that presumes everything is okay as long as a major version bump hasn't occurred - obviously it was not okay in this instance.

If semver isn't going to be followed when making breaking changes, but dynamic dependency versions are going to be defined in every first-party Aurelia project, then you are guaranteed to end up breaking things for the consumer of the packages, as evidenced by the current situation of anyone trying to install `aurelia-bootstrapper` and `aurelia-ui-virtualization` today.

>  as it would unnecessarily create more trouble

This may have caused more trouble for you as maintainers, but as the end-user of your product this has caused the ultimate trouble of breaking all apps just by simply running `npm install` on a different day, without changing a single line of code in any of the project or anything in the `package.json`.

**Comment by 3cp** [comment]
The duplicated version sounds like from an existing lock file. Once you remove all node_modules and lock file, the version should be resolved to just one.

**Comment by bigopon** [comment]
It seems there are 2 matters being conflated here:
- There's an issue by simply upgrading a core Aurelia module. Maybe applications need to declare common dependencies themselves to ensure this issue not happening again. It's not a direct issue with Aurelia.
- There's an inaccurate versioning recently in one of the Aurelia core module releases. This is because the changes isn't practically breaking: no serious applications rely on the default sanitizer.

> This may have caused more trouble for you as maintainers, but as the end-user of your product this has caused the ultimate trouble of breaking all apps just by simply running npm install on a different day, without changing a single line of code in any of the project or anything in the package.json.

Believe it or not, this causes issue to the entire Aurelia ecosystem. We had a bad experience releasing `aurelia-binding` v2 before, for a not really breaking change change, and it was a headache for folks for awhile until we had to resolve to hacks in our default CLI template.

I hope all the original questions have been answered.
