### ISSUE TITLE
unbind callback not being invoked

### ISSUE THREAD

**Issue by simonfox** [aurelia/templating-router#16]
The unbind lifecycle callback isn't being invoked.

To reproduce, just add an `unbind()` function to the welcome VM in the skeleton. When you navigate away from the welcome page, unbind doesn't get called.

**Comment by simonfox** [comment]
@EisenbergEffect 

I [think this is the commit](https://github.com/aurelia/templating-router/commit/d9f81ccad1a8ca9b4732877d81d56dde06bbcaea) where things may have gone wrong.

Then [this commit](https://github.com/aurelia/templating-router/commit/9b96894cdb532a1df2068ab7156038f43ee1afe0) switches to using `ViewSlot.remove` which doesn't do an `unbind`.

Should the `unbind` call be the responsibility of the swap strategy? I'd be happy to put together a PR if that would help?

**Comment by bryanrsmith** [comment]
Your assessment looks right to me, but maybe Rob can confirm. I think a PR would be great! Let me know if I can help.

**Comment by simonfox** [comment]
Looks like it might be more than just a `router-view` problem...The `CompositionContext.currentController` is inspected by the `CompositionEngine` [here](https://github.com/aurelia/templating/blob/master/src/composition-engine.js#L72) but I can't see `currentController` being set anywhere and it is not part of the `CompositionContext` interface.

Was it an intention to remove this property?

**Comment by simonfox** [comment]
Hi @EisenbergEffect can I get your thoughts on this?

I think the problem is not just isolated to the router, as unbind isn't getting called when using `compose` elements either.

would adding the following to the `removeAction` of [`ViewSlot.removeAt`](https://github.com/aurelia/templating/blob/master/src/view-slot.js#L181) be sufficient?
```
if (view.isBound) {
    view.unbind();
}
```

**Comment by EisenbergEffect** [comment]
Remove doesn't imply unbind. So, that's not the best fix. I can look into
it this week and issue a patch.

**Comment by jdanyow** [comment]
@briannoyes reported an issue that I traced it back to this.  

The bug causes problems with the repeat because `unbind` isn't called between calls to `bind`.

**Comment by EisenbergEffect** [comment]
I'll take care of this this week.
