### ISSUE TITLE
WITH swap-order Not working with Bluebird

### ISSUE THREAD

**Issue by joelcoxokc** [aurelia/templating-router#19]
when
router-view swap-order=“with”

Bluebirds Promise.all takes and Array, and native Promise.all uses the arguments as an Array.

We are currently using the Native Promise. 
We need to detect Bluebird, and then use the proper syntax accordingly. 
I can fix it, I just want to make sure it hasn’t already been notified!

**Comment by jdanyow** [comment]
I'm not sure if the `Promise.all(p1, p2 ... pN)` usage is standard.  MDN says `all` has one argument, an "iterable": https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

**Comment by EisenbergEffect** [comment]
I think you may be right. The bug is probably in our code and we just need to switch it to an array.
