### ISSUE TITLE
route params lose their identity

### ISSUE THREAD

**Issue by mbroadst** [aurelia/templating-router#23]
I have a case where I'm binding an instance of a class (e.g. `let thing = new MyClass({ name: 'hello', data: 42 })`) to an href to change the current route, like so:
```
<a route-href="route: detailPage; params.bind: thing">${thing.name}</a>
```

`thing` makes it into the routed VM's `activate` as the `params` object, however now it's a plain object (`Object { name: 'hello', data: 42 }`) and thus has lost any inherited properties/methods that I had wished to use when passed to that new view.

Is there any way to accomplish this? I Imagine at some point a ownProperty copy is just made of the variable, can I bypass that an pass the raw value through instead?

**Comment by EisenbergEffect** [comment]
Think about this from the perspective of browser history. The route-href literally generates an href on the a tag. It uses the params as a data source to generate the string. Then, when you click the link, the link itself triggers the history change in the browser. There's no connection to your original class. 

If you want to do something like this, I recommend that you cache the instance in some shared object cache and then retrieve it in your activate callback. However, it's important to remember, that object may not always exist, if the user is coming to the link directly.

**Comment by mbroadst** [comment]
@EisenbergEffect ah right, that makes total sense. Thanks for the explanation!
