### ISSUE TITLE
Problem with parameterized routes and getViewStrategy

### ISSUE THREAD

**Issue by mattduffield** [aurelia/templating-router#3]
I am using parameterized routes and the getViewStrategy get called the first time but any subsequent change to the route with a new parameter and the getViewStrategy is not called.  I can see that the route has indeed changed and activate method gets called every time.

**Comment by EisenbergEffect** [comment]
You will need to force the full component replace in this situation. To do that, you need to add the `determineActivationStrategy` callback to your view model:

```javascript
import {REPLACE} from 'aurelia-router`;

export class YourViewModel {
  determineActivationStrategy(){
    return REPLACE;
  }
}
```
