### ISSUE TITLE
Ability to set layoutView on parent route and the children inherit template.

### ISSUE THREAD

**Issue by TylerJPresley** [aurelia/templating-router#32]
I'd like to be able to set the layout on the parent and then the child router inherit the layout from the parent.

**Comment by charlespockert** [comment]
Sounds useful, probably a good idea to allow inheritance from the parent to be toggled per router view, and probably add a global config setting too.

**Comment by Alexander-Taran** [comment]
```
<parent>
<router-view child></router-view>
<parent>
```
to be clear: do you wish to define the layout configuration in the router that routes to parent 
and then somehow utilize it in child router?

can you provide and example of how you'd use proposed feature?

**Comment by davismj** [comment]
@TylerJPresley @charlespockert still interested in this?
