### ISSUE TITLE
The route-href attribute should work for href attributes on custom elements

### ISSUE THREAD

**Issue by thomas-darling** [aurelia/templating-router#36]
**I'm submitting a feature request**

**Expected/desired behavior:**
- **What is the expected behavior?**

The `route-href` attribute should work not just for `href` attributes on native HTML elements, such as `<a>`, but also for `href` attributes on any custom element.

In the example below, the `href` attribute of the `<a>` element will get the value `undefined`, but ideally, it should get the URL generated by `route-href`.

app-nav.html

``` html
<app-nav-item route-href="route: home" title="home">
```

app-nav-item.html

``` html
<template>
    <a href.bind="href">${title}</a>
</template>
```

app-nav-item.ts

``` typescript
export class AppNavItem
{
    @bindable
    public title: string;

    @bindable
    public href: string;
}
```
- **What is the motivation / use case for changing the behavior?**

This would make scenarios like the above cleaner, as we would not need to first generate the URL in the view model, and then bind the `href` attribute of our custom element to that value. This would make setting a `href` attribute on a custom element more consistent with how it's done for `<a>` elements, and it would cover a use case that people might expect to work.

**Comment by EisenbergEffect** [comment]
Sounds like a great opportunity to PR the route-href with this enhancement :)

**Comment by EisenbergEffect** [comment]
Fixed :)

**Comment by obedm503** [comment]
this should be documented somewhere
