### ISSUE TITLE
It should be possible to specify the router to use for the route-href attribute

### ISSUE THREAD

**Issue by rmja** [aurelia/templating-router#40]
**I'm submitting a feature request**
- **Library Version:**
  1.0.0

**Current behavior:**
`route-href` always uses the router of the current view.

**Expected/desired behavior:**
It would be nice if one could set/override the router to use on the `route-href`. Something like:

```
<a route-href="route: child-router-routename; router.bind: someOtherChildRouter">/a>
```

That would allow for navigation between child routers, where one component can take the child router of another as a dependency, and generate a link from it.

**Comment by EisenbergEffect** [comment]
Can you explain this a bit more? It wouldn't be hard to implement I don't think, but I'd like to understand your scenario and maybe see an example where you would want this and how you would reference the other routers.

**Comment by rmja** [comment]
Sure. Say that I have a navigation component as follows:
```
import {autoinject} from 'aurelia-framework';
import {AppRouter} from 'aurelia-router';
import {SettingsRouter} from './settings/settings-router';

@autoinject()
export class NavigationComponent {
    constructor(public appRouter: AppRouter, private settingsRouter: SettingsRouter) {
    }
}
```
And a `SettingsRouter` child router:
```
import {Router, RouterConfiguration} from 'aurelia-router';

export const routes = [
    { route: 'units', name: 'units', moduleId: './units', title: 'Units' }
];

export class SettingsRouter {
    public router: Router;

    configureRouter(config: RouterConfiguration, router: Router) {        
        config.map(routes);
        this.router = router;
    }
}
```

In the navigation component, I want to generate links for both the appRouter and settingsRouter; something like this:

```
<template>
<a route-href="route: dashboard; router.bind: appRouter">Main dashboard</a>
<a route-href="route: units; router.bind: settingsRouter">Units</a>
</template>
```

I know that the `SettingsRouter` is not configured if it is not the current route, but I was planning on using it together with a child router loading strategi similar to this one: http://www.jeremyg.net/entry/create-a-menu-with-child-routes-using-aurelia. Maybe with some kind of childRoutes hint such as in https://github.com/heruan/aurelia-route-mapper

**Comment by EisenbergEffect** [comment]
That sounds reasonable. @rmja  Would you at all be interested in creating a PR to add the feature. If you did that we could probably merge it and get it released fairly easily.

**Comment by rmja** [comment]
Sounds good to me. I will do it when I know for sure that I will need it. It depends somewhat on which child router loading strategy I settle on.

Btw. Thank you so much for a fantastic framework. It is such a joy to work with!

**Comment by rmja** [comment]
I am closing this one as I have found that [aurelia-route-mapper](https://github.com/heruan/aurelia-route-mapper) is a much better way forward.
