### ISSUE TITLE
Cannot use custom elements

### ISSUE THREAD

**Issue by ErikSchierboom** [aurelia/templating-router#43]
**I'm submitting a bug report**

* **Library Version:**
1.0.7

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.7.0

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
Aurelia CLI 0.21.0

* **Browser:**
all

* **Language:**
TypeScript 2.0.7

**Current behavior:**
If you include a custom element that doesn't use binding in a layoutView template file, that custom element is rendered correctly. However, if the custom element uses any binding, the element is not rendered. 

This is how to repro:

- Create a file `src/custom-header.ts`:

```typescript
export class CustomHeader {    
    public message = "Hello!";
}
```

- Create a file `src/custom-header.html`:

```html
<!DOCTYPE html>
<template>
    Custom header ${hello}
</template>
```

- Modify the `configure` function in the `src/main.ts` file to include the custom element as a global resource:

```typescript
aurelia.use
  .standardConfiguration()
  .globalResources('./custom-header');
```

- Modify the `src/app.ts` file to setup routing:

```typescript
import {RouterConfiguration, Router} from "aurelia-router";

export class App {
  public router: Router;

  configureRouter(config: RouterConfiguration, router: Router) {
    this.router = router;

    config.map([
      { 
        route: "", 
        name: "home", 
        moduleId: "home/home", 
        layoutView: 'layouts/default.html' 
      }
    ])    
  }
}
```

- Create a file `src/layout/default.html`:

```html
<!DOCTYPE html>
<template>
    <custom-header></custom-header>

    <slot name="main-content"></slot>
</template>
```

- Modify `src/app.html` to define a router view:

```html
<!DOCTYPE html>
<template>
  <h1>Aurelia layoutView binding</h1>

  <router-view></router-view>
</template>
```

- Create a file `src/home/home.html`:

```html
<!DOCTYPE html>
<template>   
    <div slot="main-content">
        Home
    </div>
</template>
```

- Create a file `src/home/home.ts`:

```typescript
export class Home {
    
}
```

Run the application and the `<custom-header>` element will not be rendered. Replacing `${hello}` with `${1+1}` also causes the element to not be rendered If you remove the binding expression, the element *does* render. 

Including the  `<custom-header>` element in the `src/home.html` file works fine, with or without binding.

**Expected/desired behavior:**
Including a custom element (that uses binding) in the layoutView template file should correctly render the custom element. In other words, binding should work for custom elements that are included in the layoutView template.

* **What is the motivation / use case for changing the behavior?**
I would like to be able to include custom elements that use binding from the layoutView.

**Comment by ErikSchierboom** [comment]
I strongly suspect this issue is related to [issue #34](#34).

**Comment by EisenbergEffect** [comment]
Closing as duplicate.
