### ISSUE TITLE
The ‘PreviousView ’ position is misplaced

### ISSUE THREAD

**Issue by zhengxiansen** [aurelia/templating-router#53]
**I'm submitting a bug report**

> I will only Chinese , I hope the picture can express my meaning 囧.

file: [router-view.js](https://github.com/aurelia/templating-router/blob/master/src/router-view.js)
line:  :127

**before**
```javascript
let work = () => {
    // previousView  === current view
    let previousView = this.view;
    // ...
};
this.view = viewPortInstruction.controller.view;
```

**after**
```javascript
let previousView = this.view;

let work = () => {
    // let previousView = this.view;
    // ...
};
```

![image](https://cloud.githubusercontent.com/assets/7506913/22014889/b13068de-dcda-11e6-9e2a-e5d58c29c5d4.png)

**Comment by dev0x10** [comment]
I can help, you can type in Chinese.
為何你認為位置錯了？

**Comment by zhengxiansen** [comment]
因为 previousView 代表着上一个视图，但是这个变量在调用之前被改成当前视图了，注意 181 行的代码，这个是在 work 方法调用前执行，这个时候 this.view 的值就是当前待激活的视图，而再是上一个视图了，如果要获取上一个视图，就应该在覆盖之前被定义

**Comment by dev0x10** [comment]
@zhengxiansen 我不太確定為何你看到的181行內容不一樣

[https://github.com/aurelia/templating-router/blob/master/src/router-view.js#L181](https://github.com/aurelia/templating-router/blob/master/src/router-view.js#L181)

**Comment by zhengxiansen** [comment]
你的在 127 行⊙﹏⊙
![image](https://cloud.githubusercontent.com/assets/7506913/22020766/f43ff27e-dcf4-11e6-8fa4-ed296076ed7e.png)

**Comment by zhengxiansen** [comment]
不一样是因为我改了代码，因为我想使用framework7, 但是 framework7 太大了，所以我在准备自己实现 router-view , 囧~~~~~ 

但是代码的确是有问题了，this.view === previousView 输出为true

**Comment by dev0x10** [comment]
@zhengxiansen 應該 174 行 和 127行
我看了一下邏輯有一點難懂因為可能沒執行到
```javascript
this.view = viewPortInstruction.controller.view;
```

如果你可以提供sample project證明這個bug可能會比較清楚
Bug template: [https://github.com/aurelia/templating-router/blob/master/ISSUE_TEMPLATE.md](https://github.com/aurelia/templating-router/blob/master/ISSUE_TEMPLATE.md)

**Comment by zhengxiansen** [comment]
@dev0x10 

`this.view = viewPortInstruction.controller.view;` 没有执行到吗？

我需要重新发起一个，还是直接在这里附上呢

**Comment by dev0x10** [comment]
@zhengxiansen 
我不太確定但如果進到156行是不是直接return不會執行下面的

可以直接這裡附上

**Comment by zhengxiansen** [comment]
I* **Library Version:**
1.0.1

* **Operating System:**
Windows 10

* **Node Version:**
v7.2.1

* **NPM Version:**
v 4.0.3

* **JSPM OR Webpack AND Version**
aurelia-cli: 0.24.0

* **Browser:**
Chrome 57.0.2970.0

* **Language:**
TypeScript 2.1.5

我压缩包上传不了，我建立了一个临时仓库

[地址](https://github.com/zhengxiansen/aurelia-router-bug-temp-demo)

 这个仓库的代码是使用 aurelia-cli 来创建的

启动之后你可以这样尝试：

1. 直接在浏览器上看效果

2. 打开 `src/resources/elements/view-container.ts`, 注销 140 的代码, 恢复 144 行的代码, 然后再在浏览器中看效果

3. 使用 aurelia 的 `router-view` 节点 替换 src/app.html 中的 `view-container` 节点 ，并且修改 `swap-order`的值, 然后再在浏览器中看效果

4. 重新修改 src/app.html  的 `router-view`   成 `view-container` ，然后恢复成我屏蔽的代码 ，并且修改 `swap-order`的值, 然后再在浏览器中看效果

`view-container.ts` 的内容完全拷贝自 `router-view.js`, 所以如果我的修改是正确的，那就说明 那段代码的确是有问题的

**Comment by EisenbergEffect** [comment]
Can someone provide some additional information for me?

**Comment by dev0x10** [comment]
@EisenbergEffect I'll find time to test and provide necessary info, could be at this weekend

**Comment by dev0x10** [comment]
@zhengxiansen 你提供的專案我build不起來
我好像有遇過這個錯誤但我忘了解法
```javascript
http://localhost:9001/src/main.js 404 (Not Found)
```

**Comment by zhengxiansen** [comment]
@dev0x10 不会吧，这几天是过年，没空上网，那我试试重新弄一个吧，但是为什么会提示main.js是404？你的电脑也是 windows 系统吗？win 系统经常出现各种奇葩的问题

**Comment by zhengxiansen** [comment]
@dev0x10 我把源码放入 GistRun 网站上了，原来没有在哪里放是因为对 systemJs 不熟悉，并且 GistRun 网站在我们这里实在是太卡，现在卡了半天终于把代码放上去了，地址在这里 [https://gist.run/?id=4f993b4e6ae962463cef734dd35121eb](https://gist.run/?id=4f993b4e6ae962463cef734dd35121eb)

**Comment by dev0x10** [comment]
@zhengxiansen 抱歉最近沒什麼空
我們可以私聊討論這問題因為我看了Gist 也看到404
微信：yauri_i

**Comment by bbarne8** [comment]
This is an issue that is actually a resolution for an aurelia-router issue #458 swap-order="with" error.

https://github.com/aurelia/router/issues/458

I posted there with this resolution and included a link to a repository to reproduce the error.
Here is the link: https://github.com/bbarne8/AureliaSwapOrderRepro.

**Comment by mroseboom** [comment]
This issue could be closed, because this is included within the merged pr [aurelia/templating-router#55](https://github.com/aurelia/templating-router/commit/959855ad660da1fb351199982b07c17016bdfbeb)
