### ISSUE TITLE
SwapStrategies is undefined:  "cannot load 'after' of undefined"

### ISSUE THREAD

**Issue by gama410** [aurelia/templating-router#59]
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.7.4

* **NPM Version:**
4.4.4

* **JSPM OR Webpack AND Version**
using CLI 

* **Browser:**
Chrome up to date

* **Language:**
TypeScript 2.2

**Current behavior:**
When loading the app, I get  **cannot load 'after' of undefined.** and a blank screen. This appears to come from **router-view.swap()** at the following line:

`         var swapStrategy = _aureliaTemplating.SwapStrategies[_this2.swapOrder] || _aureliaTemplating.SwapStrategies.after;`

because **swapStrategies** is undefined.
I'm not at all familiar with this code but I didn't see any other reference of swapStrategies in this module so I don't know where it's supposed to be created. 
When reverting to 1.0.0, it seems to work well (and I can see swapStrategies declaration in the code).

* **What is the expected behavior?**
It should not affect the loading of the page. I have no swap-order defined on the router-view, anyway...

* **What is the motivation / use case for changing the behavior?**
Seems to prevent the app from loading

**Comment by EisenbergEffect** [comment]
Make sure all your dependencies are up to date.

**Comment by wcislom** [comment]
@EisenbergEffect I have the same issue after upgrading my project to latest aurelia release:

`_aureliaTemplating.SwapStrategies[_this2.swapOrder]  `
causes 
`ERROR [app-router] TypeError: Cannot read property 'before' of undefined`

I am sure that my dependecies are up to date.

![image](https://cloud.githubusercontent.com/assets/15823673/26819237/45fc8f5c-4a9e-11e7-84f0-468eb26d9dec.png)

How can it be fixed ?

**Comment by claq2** [comment]
One way to pull in the latest aurelia-templating is to explicitly add it to your project e.g.

    npm install --save aurelia-templating

If it's being pulled in as the dependency of another package then ncu doesn't seem to update it.
