### ISSUE TITLE
Generated links on view with space in route parameter value cut off base route

### ISSUE THREAD

**Issue by InfiniteLukeOne** [aurelia/templating-router#60]
**I'm submitting a bug report**

* **Library Version:**
1.1.0

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.10.3

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
IE 11, Chrome 60.0

* **Language:**
TypeScript 2.1

**Current behavior:**
I'm having a router hirachy of three routers:
* router A has some simple routes
* router B has a route with a route parameter
* router C has some simple routes
If the value of the route parameter of router B has a space, the generated links in the router view of router C strip away the route which is defined in router A.

Example:
- app-router (router A) has routes: animals, cars
- animal-router (router B) has routes: list, :id (details)
- details-router (router C) has routes: description, photos
When going to #/animals/Big Bird/description the generated links to the description and photos route are #/Big Bird/description and #/Big Bird/photos . The generated link to the list route is #/list .

https://gist.run/?id=664cff0293ecc38fa8fbf805a57251be

In Firefox links are generated the right way. If the route parameter value has no space, links are generated the right way in IE and Chrome, too.

**Expected/desired behavior:**

* **What is the expected behavior?**
I expect the links to be generated the same way in IE and Chrome as in Firefox, not cutting off the base route.

* **What is the motivation / use case for changing the behavior?**
Working routes

* **Additional information**
When encoding the route parameter with encodeURIComponent genaration seems to be fine. unfortunately I can't do this for every link (for example router C navigation links or redirected routes). Maybe you could encode in the aurelia router.

**Comment by InfiniteLukeOne** [comment]
Can I get a statement on this issue?

**Comment by EisenbergEffect** [comment]
@davismj I know you've recently done some work on base url and encoding. Does your recent fix address this by any chance as well?

**Comment by davismj** [comment]
Yes, this seems to be a duplicate issue and should be resolved by this. https://github.com/aurelia/router/pull/501

**Comment by InfiniteLukeOne** [comment]
Thank you, I will try it once it's released
