### ISSUE TITLE
Missing properties in typescript definition of RouteHref

### ISSUE THREAD

**Issue by deap82** [aurelia/templating-router#61]
**I'm submitting a bug report**
(In lack of better headline option ;-) )

* **Library Version:**
aurelia-templating-router 1.1.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.11.2

* **NPM Version:**
5.3.0

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
N/A

* **Language:**
TypeScript 2.4.2

**Current behavior:**
When injecting RouteHref in a custom attribute, I can not access properties such as route and router, and keep the Typescript compiler happy.
(Without resorting to routeHref['route'] instead of routeHref.route)

**Expected/desired behavior:**

* **What is the expected behavior?**
All members of the RouteHref should be included in the typescript definition.

* **What is the motivation / use case for changing the behavior?**
Being able to write custom attributes that can inspect the RouteHref attribute on the same element.
(Perhaps router could be private, but I don't see why as I can inject it separately any way).

**Comment by Alexander-Taran** [comment]
@deap82 would you like to create a PR for that?

**Comment by bigopon** [comment]
With latest changes, the interface of `RouteHref` would be:
```ts

/**
 * Helper custom attribute to help associate an element with a route by name
 */
export declare class RouteHref {
	/**
	 * Current router of this attribute
	 */
	readonly router: Router;
	/**
	 * Element this attribute is associated with
	 */
	readonly element: Element;
	/**
	 * Name of the route this attribute refers to. This name should exist in the current router hierarchy
	 */
	route: string;
	/**
	 * Parameters of this attribute to generate URL.
	 */
	params: Record<string, any>;
	/**
	 * Target property on a custom element if this attribute is put on a custom element
	 * OR an attribute if this attribute is put on a normal element
	 */
	attribute: string;
	constructor(router: Router, element: Element);
	bind(): void;
	unbind(): void;
	attributeChanged(value: any, previous: any): Promise<void>;
	processChange(): Promise<void>;
}
```
I think this can be closed @deap82 @EisenbergEffect
