### ISSUE TITLE
Error: Unable to find module with ID: aurelia-templating-router/router-view.html

### ISSUE THREAD

**Issue by Kukks** [aurelia/templating-router#63]
**I'm submitting a bug report**

* **Library Version:**
1.2.0

**Please tell us about your environment:**
* **Operating System:**
Win 10

* **Node Version:**
6.11.0

* **NPM Version:**
5.4.2

* **JSPM OR Webpack AND Version**
Webpack 3.6.0

* **Browser:**
all

* **Language:**
Ts 2.5.3

**Current behavior:**
Upon attempting to load site after a successful build:
```
Error: Unable to find module with ID: aurelia-templating-router/router-view.html
    at WebpackLoader.<anonymous> (aurelia-loader-webpack.js:187)
    at step (aurelia-loader-webpack.js:36)
    at Object.next (aurelia-loader-webpack.js:17)
    at aurelia-loader-webpack.js:11
    at initializePromise (es6-promise.js:459)
    at new Promise (es6-promise.js:871)
    at 229.__awaiter (aurelia-loader-webpack.js:7)
    at WebpackLoader.229.WebpackLoader._import (aurelia-loader-webpack.js:152)
    at WebpackLoader.<anonymous> (aurelia-loader-webpack.js:252)
    at step (aurelia-loader-webpack.js:36)
```

**Notes**
I just bumped up the versions of my aurelia packages.
```
    "aurelia-animator-css": "^1.0.3",
    "aurelia-authentication": "~3.7.0",
    "aurelia-binding": "^1.3.0",
    "aurelia-bootstrapper": "^2.1.1",
    "aurelia-configuration": "^1.0.17",
    "aurelia-dependency-injection": "^1.3.2",
    "aurelia-event-aggregator": "^1.0.1",
    "aurelia-fetch-client": "^1.1.3",
    "aurelia-framework": "^1.1.5",
    "aurelia-history": "^1.1.0",
    "aurelia-i18n": "~2.0.0",
    "aurelia-loader": "^1.0.0",
    "aurelia-logging": "^1.3.1",
    "aurelia-orm": "~6.2.0",
    "aurelia-pal": "^1.4.0",
    "aurelia-route-mapper": "^0.1.0",
    "aurelia-router": "^1.4.0",
    "aurelia-task-queue": "~1.2.1",
    "aurelia-templating": "~1.5.0",
    "aurelia-templating-binding": "^1.4.0",
    "aurelia-templating-resources": "^1.5.1",
    "aurelia-templating-router": "^1.2.0",
    "aurelia-ui-virtualization": "^1.0.0-beta.3.1.1",
```

**Comment by Kukks** [comment]
I've also tried setting my package.json to only point to `"aurelia-bootstrapper": "^2.1.1"` and still getting the issue. Really unsure of how to handle this.

**Comment by Kukks** [comment]
On another note, the previous working versions were these:
```
    "aurelia-animator-css": "^1.0.2",
    "aurelia-authentication": "~3.7.0",
    "aurelia-binding": "~1.2.2",
    "aurelia-bootstrap": "^0.1.18",
    "aurelia-bootstrapper": "~2.1.1",
    "aurelia-configuration": "^1.0.17",
    "aurelia-dependency-injection": "~1.3.1",
    "aurelia-event-aggregator": "~1.0.1",
    "aurelia-fetch-client": "~1.1.2",
    "aurelia-framework": "~1.1.2",
    "aurelia-history": "~1.0.0",
    "aurelia-i18n": "~1.6.2",
    "aurelia-loader": "~1.0.0",
    "aurelia-logging": "~1.3.1",
    "aurelia-orm": "~6.2.0",
    "aurelia-pal": "^1.3.0",
    "aurelia-route-mapper": "^0.1.0",
    "aurelia-router": "~1.3.0",
    "aurelia-task-queue": "~1.2.0",
    "aurelia-templating": "~1.4.2",
    "aurelia-templating-binding": "~1.3.0",
    "aurelia-templating-resources": "~1.4.0",
    "aurelia-templating-router": "~1.1.0",
```

**Comment by davismj** [comment]
Can you providing a working example? Perhaps using [gist.run](gist.run). This looks like an issue with how webpack is trying to load the file, but it's hard to tell.

**Comment by Kukks** [comment]
I'll try and set it up first thing tomorrow morning. I've reverted back to
my original versions and app is working that way. I guess there was some
breaking change somewhere along them.

**Comment by JeroenVinke** [comment]
@Kukks if possible, could you share the other dependencies in package.json as well, in addition to the outputs of `npm -v` and `node -v` ?

**Comment by Kukks** [comment]
@JeroenVinke  @davismj I was playing with it again and re-did the package bumps in case I missed anything: seem to work with the following: 
```
 "devDependencies": {
    "@types/jest": "21.1.2",
    "@types/lodash": "4.14.77",
    "@types/node": "8.0.32",
    "@types/webpack": "3.0.13",
    "aurelia-loader-nodejs": "1.0.1",
    "aurelia-pal-nodejs": "1.0.0-beta.2.0.0",
    "aurelia-protractor-plugin": "1.0.5",
    "aurelia-testing": "1.0.0-beta.3.0.1",
    "aurelia-webpack-plugin": "2.0.0-rc.5",
    "autoprefixer": "7.1.4",
    "awesome-typescript-loader": "3.2.3",
    "copy-webpack-plugin": "4.1.0",
    "cross-env": "5.0.5",
    "css-loader": "0.28.7",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "3.0.1",
    "file-loader": "1.1.4",
    "html-webpack-plugin": "2.30.1",
    "http-server": "0.10.0",
    "istanbul-instrumenter-loader": "3.0.0",
    "jasmine-core": "2.8.0",
    "jest": "21.2.1",
    "jest-cli": "21.2.1",
    "json-loader": "0.5.7",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-jasmine": "1.1.0",
    "karma-mocha-reporter": "2.2.4",
    "karma-webpack": "2.0.4",
    "nps": "5.7.1",
    "nps-utils": "1.4.0",
    "postcss-loader": "2.0.6",
    "protractor": "5.1.2",
    "style-loader": "0.19.0",
    "ts-jest": "21.0.1",
    "ts-node": "3.3.0",
    "typescript": "2.5.3",
    "url-loader": "0.6.1",
    "wait-on": "2.0.2",
    "webpack": "3.6.0",
    "webpack-dev-server": "2.9.1",
    "@types/hammerjs": "~2.0.34",
    "@types/nprogress": "0.0.29",
    "@types/prismjs": "~1.6.1",
    "@types/reflect-metadata": "0.0.5",
    "@types/webpack-env": "~1.13.0",
    "node-sass": "^4.5.2",
    "sass-loader": "^6.0.3",
    "svg-inline-loader": "~0.8.0",
    "ts-nameof": "^0.10.2",
    "ts-nameof-loader": "^1.0.1",
    "tslint": "~5.7.0",
    "tslint-loader": "~3.5.3"
  },
  "dependencies": {
    "aurelia-animator-css": "~1.0.3",
    "aurelia-binding": "~1.3.0",
    "aurelia-bootstrapper": "~2.1.1",
    "aurelia-dependency-injection": "~1.3.2",
    "aurelia-event-aggregator": "~1.0.1",
    "aurelia-fetch-client": "~1.1.3",
    "aurelia-framework": "~1.1.5",
    "aurelia-history": "~1.1.0",
    "aurelia-loader": "~1.0.0",
    "aurelia-logging": "~1.3.1",
    "aurelia-orm": "~6.2.0",
    "aurelia-pal": "~1.4.0",
    "aurelia-router": "~1.4.0",
    "aurelia-task-queue": "~1.2.1",
    "aurelia-templating": "~1.5.0",
    "aurelia-templating-binding": "~1.4.0",
    "aurelia-templating-resources": "~1.5.1",
    "aurelia-templating-router": "~1.2.0",
    "aurelia-ui-virtualization": "~1.0.0-beta.3.1.1",
    "aurelia-route-mapper": "~0.1.0",
    "aurelia-i18n": "~2.0.0",
    "aurelia-configuration": "~1.0.17",
    "aurelia-authentication": "~3.7.0",
    "aurelia-validation": "~1.1.1",
    "bootstrap": "~4.0.0-beta",
    "bootstrap-purr": "github:softwarespot/jquery-bootstrap-purr",
    "choices.js": "~3.0.2",
    "clipboard": "~1.7.1",
    "custom-event-polyfill": "~0.3.0",
    "es6-promise-promise": "~1.0.0",
    "flatpickr": "~3.0.7",
    "gridstack": "github:troolee/gridstack.js#8e4898557ee9f09b0f0bd576535d3f6ad277660d",
    "gulp": "github:gulpjs/gulp#4.0",
    "hammerjs": "~2.0.8",
    "hesehus-js-breakpoint": "~1.0.1",
    "i18next": "~9.0.1",
    "i18next-browser-languagedetector": "~2.0.0",
    "i18next-fetch-backend": "~0.1.0",
    "i18next-localstorage-cache": "~1.1.1",
    "intl": "~1.2.5",
    "isomorphic-fetch": "~2.2.1",
    "jquery": "~3.2.1",
    "jquery-ui": "~1.12.1",
    "keycode": "~2.1.9",
    "localforage": "~1.5.0",
    "moment": "~2.18.1",
    "nouislider": "~10.1.0",
    "nprogress": "~0.2.0",
    "popper.js": "~1.12.5",
    "prismjs": "~1.8.1",
    "raf": "~3.4.0",
    "raw-loader": "~1.0.0-beta.0",
    "reflect-metadata": "~0.1.10",
    "requirejs": "~2.3.5",
    "select2": "~4.0.4",
    "selectize": "~0.12.4",
    "sweetalert2": "~6.10.1",
    "text": "github:requirejs/text#latest",
    "webcomponents.js": "github:webcomponents/webcomponentsjs#v0"
  }
```
node
```
node -v
v6.11.0
npm -v
5.4.2
```

**Comment by davismj** [comment]
@Kukks Thanks for taking the time to investigate and follow up. That's a huge help to us. Glad everything is working, Andrew.

**Comment by MrBliz** [comment]
@davismj  I'm having the same issue. Matching my packages to the same ones @Kukks has does not fix it, nor does changing packages to the ones in the referenced issue.

Reproducible sample attached. (Dotnet)

[WebClient.zip](https://github.com/aurelia/templating-router/files/1368143/WebClient.zip)

**Comment by kuechlerm** [comment]
This is quite mysterious. I have two projects. One is working with
        "aurelia-templating-binding": "1.4.0",
        "aurelia-templating-resources": "1.5.1",
        "aurelia-templating-router": "1.2.0",

The other one shows the mentioned error "Unable to find module with ID: aurelia-templating-router/router-view.html".

Both have the exact same webpack setup with the same aurelia packages and versions.

Any ideas?

**Comment by sboyd** [comment]
For what it's worth I got the same error when I upgraded from "aurelia-templating-router": "^1.0.0", -> "aurelia-templating-router": "^1.2.0".

I'm in the process of upgrading my aurelia-* packages. I ran npm update and had to roll back. Proceeded to do one package at a time and when I got to aurelia-templating-router that's when I go the same error as mentioned above.

Thanks --Steve

**Comment by kuechlerm** [comment]
Glad I'm not alone with this...

@davismj can you reopen this? I'm out of options.

**Comment by Kukks** [comment]
Maybe you can try and setting the deps to point to only aurelia-bootstrapper. Try also removing the npm_modules folder and to check after a fresh install if all the aurelia modules installed are the correct versions. Could be another package demanding a lower version of one specific aurelia package

**Comment by kuechlerm** [comment]
@Kukks Thanks for your tip!

I changed my package.json from (only aurelia packages shown):
```
        "aurelia-bootstrapper": "2.1.1",
        "aurelia-event-aggregator": "1.0.1",
        "aurelia-fetch-client": "1.1.3",
        "aurelia-framework": "1.1.5",
        "aurelia-history-browser": "1.1.0",
        "aurelia-loader-webpack": "2.1.0",
        "aurelia-logging-console": "1.0.0",
        "aurelia-pal": "1.4.0",
        "aurelia-pal-browser": "1.3.0",
        "aurelia-polyfills": "1.2.2",
        "aurelia-route-recognizer": "1.1.1",
        "aurelia-router": "1.4.0",
        "aurelia-templating-binding": "1.3.0",
        "aurelia-templating-resources": "1.4.0",
        "aurelia-templating-router": "1.1.0",
```

To
```
        "aurelia-bootstrapper": "2.1.1",
        "aurelia-fetch-client": "1.1.3",
```

Now it works! 

I used to specify all aurelia packages due to problems with different versions of npm and yarn. Sometimes packages were not included if not specified.

Some aurelia package seems to cause the issue, but I can live with this setup for the moment.

Thank you.

**Comment by Lichtjaeger** [comment]
It doesn't work for me.
For now, I changed my dependencies to
```
        "aurelia-bootstrapper": "^2.1.1",
        "aurelia-loader-nodejs": "^1.0.1",
        "aurelia-templating-resources": "1.4.0",
        "aurelia-templating-router": "^1.1.0",
```

This is working for my electron(-compile v6.4.2) app.

**Comment by davismj** [comment]
@Lichtjaeger @Kukks @kuechlerm 

I'm not exactly sure the source of the issue. It's not a router issue; it's a more general module loading issue, I believe. See here for a similar error in the templating-resources library: https://github.com/aurelia/templating-resources/issues/312.

It also seems to be specific to an update with both Aurelia and then webpack loader. Where possible I always use systemjs so I don't have a lot of personal experience with this issue.

Let me ping the team internally to see if someone can point me in the right direction to close out this issue once and for all. Maybe there is in fact something we can do in the router library to resolve this.

Thanks for patience, everyone.

**Comment by JeroenVinke** [comment]
Hey everyone, do any of you have yarn.lock or package-lock.json files? Could you try and remove those, together with node_modules and `yarn` or `npm install` again? Let me know how that goes.

**Comment by sboyd** [comment]
Hi @JeroenVinke I do have a package-lock.json file. I'll delete it as well as my node_modules file and then try upgrading to the latest aurelia-templating-router package

**Comment by sboyd** [comment]
@JeroenVinke I just tried it and it seems to have worked, but now I'm getting the attached warnings in the browser console. I'm going to see if I'm able to follow similar steps with the aurelia-templating-binding and aurelia-templating-resources packages.

![image](https://user-images.githubusercontent.com/219548/31922606-323068d8-b833-11e7-969f-b0bc49cde2ac.png)

**Comment by Lichtjaeger** [comment]
Removing the package-lock.json file worked.

Now I only have "aurelia-bootstrapper" and "aurelia-loader-nodejs" in my dependencies.

And I don't have any warnings, unlike @sboyd .

**Comment by dkent600** [comment]
What worked for me:

Per @kuechlerm, reducing the packages in package.json down to:
```
"aurelia-bootstrapper": "2.1.1",
"aurelia-fetch-client": "1.1.3",
```

Per @Lichtjaeger , removing the package-lock.json file 

Thanks

**Comment by sboyd** [comment]
Just so I'm clear @dkent600 you're saying I can trim all this down to just two packages.

"aurelia-bootstrapper-webpack": "^1.1.0",
"aurelia-event-aggregator": "^1.0.0",
"aurelia-fetch-client": "^1.0.1",
"aurelia-framework": "^1.1.5",
"aurelia-froala-editor": "^2.7.3",
"aurelia-google-maps": "^1.0.21",
"aurelia-history-browser": "^1.1.0",
"aurelia-loader-webpack": "^1.0.3",
"aurelia-logging-console": "^1.0.0",
"aurelia-pal-browser": "^1.0.0",
"aurelia-polyfills": "^1.1.1",
 "aurelia-route-recognizer": "^1.1.1",
 "aurelia-router": "^1.4.0",
 "aurelia-templating-binding": "^1.4.0",
 "aurelia-templating-resources": "^1.5.2",
 "aurelia-templating-router": "^1.2.0",
 "aurelia-validation": "^1.1.2"

To only having two packages?
"aurelia-bootstrapper": "2.1.1",
"aurelia-fetch-client": "1.1.3",

**Comment by dkent600** [comment]
@sboyd  Certainly not all of those, but I most of them.  aurelia-bootstrapper has a lot of dependencies.  You can see them listed in its own package.json.

**Comment by sboyd** [comment]
@dkent600 out of curiosity what Aurelia template did you start your project with? https://github.com/aurelia/skeleton-navigation I'm using the ESNext webpack template. I'm curious because I don't have an aurelia-bootstrapper package but I have a aurelia-bootstrapper-webpack package.

**Comment by dkent600** [comment]
@sboyd I started with Aurelia-Typescript-Webpack

**Comment by sboyd** [comment]
Thank you @dkent600

**Comment by sboyd** [comment]
Sorry to keep spamming everyone, but @JeroenVinke any idea how to get rid of the warnings I'm regarding chunks?

https://user-images.githubusercontent.com/219548/31922606-323068d8-b833-11e7-969f-b0bc49cde2ac.png

**Comment by JeroenVinke** [comment]
@jods4 any thoughts on the warnings that @sboyd is getting?

**Comment by sboyd** [comment]
@jods4 and @JeroenVinke I think I'm ok now. I commented out, and will soon delete, the first line under entry in my webpack.config.bable.js file and the warning is gone now and the app seems to still work ok.

let config = generateConfig(
  {
    entry: {
      //'app': ['./src/main' /* this is filled by the aurelia-webpack-plugin */],
      'aurelia-bootstrap': coreBundles.bootstrap,
      'aurelia': coreBundles.aurelia.filter(pkg => coreBundles.bootstrap.indexOf(pkg) === -1)
    },
    output: {
      path: outDir,
      filename: "[name].[chunkhash].js"
    }
  },

**Comment by dmoebius** [comment]
For anyone stumbling upon the same issue and landing here: in my case it helped to delete the `node_modules` folder, then run `npm install` and **then run `npm dedupe`!** The last part made the difference.

**Comment by Alexander-Taran** [comment]
@dmoebius 
You probably use npm and you have package.lock.json
Delete that file and node_modules and reinstall dependencies.

It is an npm issue 

It was discussed a lot @ https://discourse.aurelia.io/
and in https://gitter.im/aurelia/Discuss
