### ISSUE TITLE
Missing properties in typescript definition files

### ISSUE THREAD

**Issue by gama410** [aurelia/templating-router#77]
**I'm submitting a bug report**

* **Library Version:**
1.3.1

**Please tell us about your environment:**
* **Operating System:**
irrelevant

* **Node Version:**
irrelevant

* **NPM Version:**
irrelevant

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
all 

* **Language:**
Typescript

**Current behavior:**

I already posted this problem I have in aurelia-dependency-injection ( [here](https://github.com/aurelia/dependency-injection/issues/163#issuecomment-391622161) ).

This is not really a bug in itself. I'm currently retrieving the parent page (from which a navigation has been initiated) from the navigation instruction passed to my child route in its activate method.
In the navigation instruction, I can get the container (through instruction.router.container) which itself contains a viewModel property which is my parent's viewModel.
My small problem is that this property is not defined in the Container d.ts interface so typescript echoes an error if I don't cast the Container as 'any' in my code.
Now, I see that this property is indeed not set in aurelia-dependency-injection but rather in aurelia-router or aurelia-templating-router and I suppose it is a remnant of the fact that all developments were done in JS instead of TS in the beginning. Wouldn't it be possible to add this property to the d.ts so it would provide a coherent interface?
Or maybe this property is not meant to be used at all?

**Expected/desired behavior:**

* **What is the expected behavior?**
I would expect the viewModel property to be defined in the Container d.ts interface

* **What is the motivation / use case for changing the behavior?**
For consistency's sake...

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect correct me if I'm wrong, but isn't this a `private`/`internal` *API*/*implementation detail*?

**Comment by EisenbergEffect** [comment]
Yes. Definitely internal. I really wish we didn't even have those properties. Please don't count on them...

**Comment by gama410** [comment]
Ok thank you!

Just for my information, how can one know that a property is internal or private? In this particular case, except for the fact that it was not referenced in the d.ts, I couldn't find anything special about it (no decorator, comment or leading underscore in front of the variable name)...

And as a second question, is there a valid way for me to retrieve the parent view model of a component in its activate() method call?

**Comment by gama410** [comment]
Indeed, it would be the simplest way but I use a base view model that has to be implemented by all page components. I define the activate method in the base vm so I cannot inject things in it. I can use the Container singleton directly (Container.instance.get... )but won't I get the app container instead of the parent one? So can I be sure I will get the correct data?

**Comment by davismj** [comment]
Use the created callback to grab the owning View.

**Comment by gama410** [comment]
Great, thank you!
