### ISSUE TITLE
Reminder to release 1.3.2

### ISSUE THREAD

**Issue by PWKad** [aurelia/templating-router#80]
Currently since the version is unreleased starting a new project fails because of forks for binding being created.  As I checked this is the last package that needs to be released (bootstrapper and the other ones in the skeletons can be fixed by running updates on all of the packages) so please release when you have time this week!

**Comment by EisenbergEffect** [comment]
100% agree. @davismj Is it safe to release templating-router master? We need to get this out ASAP since it's causing problems.

**Comment by EisenbergEffect** [comment]
Working on a release now. We think it should all be safe. Hang tight. It's on the way.

**Comment by EisenbergEffect** [comment]
Released!

**Comment by rmja** [comment]
Fantastic, things seems coherent again! Thanks @EisenbergEffect for a fast fix!
