### ISSUE TITLE
Upgrading from 1.3.1 to 1.3.2

### ISSUE THREAD

**Issue by djedi** [aurelia/templating-router#82]
Upgrading from 1.3.1 to 1.3.2 broke so many things in our project. Because of its dependencies, I would think this would be a Major Update rather than a Patch Update.

**Comment by EisenbergEffect** [comment]
@djedi We apologize for the inconvenience. At the time we must not have realized this was going to cause issues. Is there anything we can do fix things for you?

**Comment by davismj** [comment]
@djedi what broke?

**Comment by Alexander-Taran** [comment]
Can be closed
